language: php
sudo: false
php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --dev --no-interaction -d "$(pwd)/frontend/"

script:
  - cd frontend
  - npm install
  - bower install
  - gulp
  - cd ..
  - mkdir -p build/logs
  - (cd "$(pwd)/frontend/"; phpunit)
