# ╔════════════════════════════════════════════════════════════════════════════╗
# ║                                                                            ║
# ║              _ \                                           |               ║
# ║             |   | _` | __ \   _ \  __|\ \  \   / _ \   __| |  /            ║
# ║             ___/ (   | |   |  __/ |    \ \  \ / (   | |      <             ║
# ║            _|   \__,_| .__/ \___|_|     \_/\_/ \___/ _|   _|\_\            ║
# ║                       _|                                                   ║
# ║                                                                            ║
# ║           * github.com/paperwork * twitter.com/paperworkcloud *            ║
# ║                                                                            ║
# ╚════════════════════════════════════════════════════════════════════════════╝
version: '3.7'

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Networks                                                                   ║
# ║                                                                            ║
# ║ Please make sure to create this network before launching this stack        ║
# ║ file, otherwise composer won't be able to deploy.                          ║
# ╚════════════════════════════════════════════════════════════════════════════╝
networks:
  papernet:
    driver: overlay
    driver_opts:
      encrypted: "true"

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Services                                                                   ║
# ╚════════════════════════════════════════════════════════════════════════════╝
services:

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Traefik                                                                    ║
# ╚════════════════════════════════════════════════════════════════════════════╝
  traefik:
    image: traefik:alpine
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/acme.json:/acme.json
    networks:
      - papernet
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 360s
      labels:
        - "traefik.frontend.rule=Host:${PAPERWORK_DOMAIN:-paperwork.local}"
        - "traefik.port=8080"

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Collections (database)                                                     ║
# ╚════════════════════════════════════════════════════════════════════════════╝
  service_collections:
    image: mongo:latest
    command: --wiredTigerCacheSizeGB 1.5
    volumes:
      - type: bind
        source: ./volumes/mongodb
        target: /data/db
    networks:
      - papernet
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 360s

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ File storage                                                               ║
# ╚════════════════════════════════════════════════════════════════════════════╝
  service_storages_backend:
    image: minio/minio:latest
    command: server --address ':8080' /data
    environment:
      MINIO_ACCESS_KEY: root
      MINIO_SECRET_KEY: roooooot
    volumes:
      - type: bind
        source: ./volumes/minio
        target: /data
    networks:
      - papernet
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 360s

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Message broker                                                             ║
# ╚════════════════════════════════════════════════════════════════════════════╝
  service_events:
    image: rabbitmq:alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: 'D]v!y;>nR!796v)S,R9J,J!zb^,a;m{:I0u^{2;\{\{82FV5p9YtUisT&,<4L$KC(^'
    volumes:
      - type: bind
        source: ./volumes/rabbitmq
        target: /var/lib/rabbitmq
    networks:
      - papernet
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 360s

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Gatekeeper Service                                                         ║
# ╚════════════════════════════════════════════════════════════════════════════╝
  service_gatekeeper:
    image: paperwork/service-gatekeeper:latest
    environment:
      CONFIG_JSON: '{"port":8080,"jwt_secret":"${PAPERWORK_JWT_SECRET:-ru4XngBQ/uXZX4o/dTjy3KieL7OHkqeKwGH9KhClVnfpEaRcpw+rNvvSiC66dyiY}","services":[{"name":"users","target":"http://service_users:8080","endpoints":["/users","/registration","/login"]},{"name":"notes","target":"http://service_notes:8080","endpoints":["/notes"]},{"name":"storages","target":"http://service_storages:8080","endpoints":["/attachments"]},{"name": "profile_photos","target": "http://service_storages:8080","endpoints": ["/profile_photos"]}]}'
    networks:
      - papernet
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 60s
      labels:
        - "traefik.enable=true"
        - "traefik.protocol=http"
        - "traefik.port=8080"
        - "traefik.docker.network=papernet"
        - "traefik.backend=service_gatekeeper"
        - "traefik.backend.loadbalancer.swarm=true"
        - "traefik.frontend.entryPoints=http"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.rule=Host:${PAPERWORK_API_HOSTNAME:-api}.${PAPERWORK_DOMAIN:-paperwork.local};PathPrefix:/"

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Configs Service                                                            ║
# ╚════════════════════════════════════════════════════════════════════════════╝
  service_configs:
    image: paperwork/service-configs:latest
    environment:
      PORT: 8080
      MONGODB_URL: mongodb://service_collections:27017/configs
      INTERNAL_RESOURCE_CONFIGS: http://service_configs:8080/internal/configs
      INTERNAL_RESOURCE_USERS: http://service_users:8080/internal/users
      INTERNAL_RESOURCE_NOTES: http://service_notes:8080/internal/notes
      INTERNAL_RESOURCE_ATTACHMENTS: http://service_storages:8080/internal/attachments
      INTERNAL_RESOURCE_JOURNALS: http://service_journals:8080/internal/journals
    networks:
      - papernet
    depends_on:
      - service_collections
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Users Service                                                              ║
# ╚════════════════════════════════════════════════════════════════════════════╝
  service_users:
    image: paperwork/service-users:latest
    environment:
      PORT: 8080
      JWT_SECRET: "${PAPERWORK_JWT_SECRET:-ru4XngBQ/uXZX4o/dTjy3KieL7OHkqeKwGH9KhClVnfpEaRcpw+rNvvSiC66dyiY}"
      MONGODB_URL: mongodb://service_collections:27017/users
      INTERNAL_RESOURCE_CONFIGS: http://service_configs:8080/internal/configs
      INTERNAL_RESOURCE_USERS: http://service_users:8080/internal/users
      INTERNAL_RESOURCE_NOTES: http://service_notes:8080/internal/notes
      INTERNAL_RESOURCE_ATTACHMENTS: http://service_storages:8080/internal/attachments
      INTERNAL_RESOURCE_JOURNALS: http://service_journals:8080/internal/journals
    networks:
      - papernet
    depends_on:
      - service_collections
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Notes Service                                                              ║
# ╚════════════════════════════════════════════════════════════════════════════╝
  service_notes:
    image: paperwork/service-notes:latest
    environment:
      PORT: 8080
      MONGODB_URL: mongodb://service_collections:27017/notes
      INTERNAL_RESOURCE_CONFIGS: http://service_configs:8080/internal/configs
      INTERNAL_RESOURCE_USERS: http://service_users:8080/internal/users
      INTERNAL_RESOURCE_NOTES: http://service_notes:8080/internal/notes
      INTERNAL_RESOURCE_ATTACHMENTS: http://service_storages:8080/internal/attachments
      INTERNAL_RESOURCE_JOURNALS: http://service_journals:8080/internal/journals
    networks:
      - papernet
    depends_on:
      - service_collections
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Storages Service                                                           ║
# ╚════════════════════════════════════════════════════════════════════════════╝
  service_storages:
    image: paperwork/service-storages:latest
    environment:
      PORT: 8080
      MONGODB_URL: mongodb://service_collections:27017/storages
      STORAGE_URL: http://service_storages_backend:8080
      AWS_ACCESS_KEY_ID: root
      AWS_SECRET_ACCESS_KEY: roooooot
      INTERNAL_RESOURCE_CONFIGS: http://service_configs:8080/internal/configs
      INTERNAL_RESOURCE_USERS: http://service_users:8080/internal/users
      INTERNAL_RESOURCE_NOTES: http://service_notes:8080/internal/notes
      INTERNAL_RESOURCE_ATTACHMENTS: http://service_storages:8080/internal/attachments
      INTERNAL_RESOURCE_JOURNALS: http://service_journals:8080/internal/journals
    networks:
      - papernet
    depends_on:
      - service_collections
      - service_storages_backend
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Journals Service                                                           ║
# ╚════════════════════════════════════════════════════════════════════════════╝
  service_journals:
    image: paperwork/service-journals:latest
    environment:
      PORT: 8080
      MONGODB_URL: mongodb://service_collections:27017/journals
      EVENTS_URL: amqp://service_events
      INTERNAL_RESOURCE_CONFIGS: http://service_configs:8080/internal/configs
      INTERNAL_RESOURCE_USERS: http://service_users:8080/internal/users
      INTERNAL_RESOURCE_NOTES: http://service_notes:8080/internal/notes
      INTERNAL_RESOURCE_ATTACHMENTS: http://service_storages:8080/internal/attachments
      INTERNAL_RESOURCE_JOURNALS: http://service_journals:8080/internal/journals
    networks:
      - papernet
    depends_on:
      - service_collections
      - service_events
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Web UI                                                                     ║
# ╚════════════════════════════════════════════════════════════════════════════╝
  web:
    image: paperwork/web:latest
    environment:
      NGINX_HOST: "${PAPERWORK_WEB_HOSTNAME:-www}.${PAPERWORK_DOMAIN:-paperwork.local}"
      NGINX_PORT: 80
      PAPERWORK_API_GATEWAY_PROTOCOL: "${PAPERWORK_API_PROTOCOL:-http}"
      PAPERWORK_API_GATEWAY_HOST_PORT: "${PAPERWORK_API_HOSTNAME:-api}.${PAPERWORK_DOMAIN:-paperwork.local}"
    networks:
      - papernet
    depends_on:
      - service_gatekeeper
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.protocol=http"
        - "traefik.port=80"
        - "traefik.docker.network=papernet"
        - "traefik.backend=web"
        - "traefik.backend.loadbalancer.swarm=true"
        - "traefik.frontend.entryPoints=http"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.rule=Host:${PAPERWORK_WEB_HOSTNAME:-www}.${PAPERWORK_DOMAIN:-paperwork.local};PathPrefix:/"
