# ╔════════════════════════════════════════════════════════════════════════════╗
# ║                                                                            ║
# ║              _ \                                           |               ║
# ║             |   | _` | __ \   _ \  __|\ \  \   / _ \   __| |  /            ║
# ║             ___/ (   | |   |  __/ |    \ \  \ / (   | |      <             ║
# ║            _|   \__,_| .__/ \___|_|     \_/\_/ \___/ _|   _|\_\            ║
# ║                       _|                                                   ║
# ║                                                                            ║
# ║           * github.com/paperwork * twitter.com/paperworkcloud *            ║
# ║                                                                            ║
# ╚════════════════════════════════════════════════════════════════════════════╝
version: '3.7'

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Networks                                                                   ║
# ║                                                                            ║
# ║ Please make sure to create this network before launching this stack        ║
# ║ file, otherwise composer won't be able to deploy.                          ║
# ╚════════════════════════════════════════════════════════════════════════════╝
networks:
  papernet:
    driver: overlay
    driver_opts:
      encrypted: "true"

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Services                                                                   ║
# ╚════════════════════════════════════════════════════════════════════════════╝
services:

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Traefik                                                                    ║
# ╚════════════════════════════════════════════════════════════════════════════╝
  traefik:
    image: traefik:alpine
    env_file:
      - env/traefik.env
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/acme.json:/acme.json
    networks:
      - papernet
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 360s
      labels:
        - "traefik.frontend.rule=Host:${PAPERWORK_DOMAIN:-paperwork.local}"
        - "traefik.port=8080"

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Collections (database)                                                     ║
# ╚════════════════════════════════════════════════════════════════════════════╝
  service_collections:
    image: mongo:latest
    env_file:
      - env/service_collections.env
    command: --wiredTigerCacheSizeGB 0.25
    volumes:
      - type: bind
        source: ./volumes/mongodb
        target: /data/db
    networks:
      - papernet
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 360s
      labels:
        - "traefik.enable=false"

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ File storage                                                               ║
# ╚════════════════════════════════════════════════════════════════════════════╝
  service_storages_backend:
    image: minio/minio:latest
    command: server --address ':8080' /data
    env_file:
      - env/service_storages_backend.env
    volumes:
      - type: bind
        source: ./volumes/minio
        target: /data
    networks:
      - papernet
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 360s
      labels:
        - "traefik.enable=false"

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Message broker                                                             ║
# ╚════════════════════════════════════════════════════════════════════════════╝
  service_events:
    image: rabbitmq:alpine
    env_file:
      - env/service_events.env
    volumes:
      - type: bind
        source: ./volumes/rabbitmq
        target: /var/lib/rabbitmq
    networks:
      - papernet
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 360s
      labels:
        - "traefik.enable=false"

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Gatekeeper Service                                                         ║
# ╚════════════════════════════════════════════════════════════════════════════╝
  service_gatekeeper:
    image: paperwork/service-gatekeeper:latest
    env_file:
      - env/service_gatekeeper.env
    networks:
      - papernet
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 60s
      labels:
        - "traefik.enable=true"
        - "traefik.protocol=http"
        - "traefik.port=8080"
        - "traefik.docker.network=paperwork_papernet"
        - "traefik.backend=service_gatekeeper"
        - "traefik.backend.loadbalancer.swarm=true"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.rule=Host:${PAPERWORK_API_HOSTNAME:-api}.${PAPERWORK_DOMAIN:-paperwork.local};PathPrefix:/"

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Configs Service                                                            ║
# ╚════════════════════════════════════════════════════════════════════════════╝
  service_configs:
    image: paperwork/service-configs:latest
    env_file:
      - env/service_configs.env
      - env/services_internal.env
    networks:
      - papernet
    depends_on:
      - service_collections
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=false"

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Users Service                                                              ║
# ╚════════════════════════════════════════════════════════════════════════════╝
  service_users:
    image: paperwork/service-users:latest
    env_file:
      - env/service_users.env
      - env/services_internal.env
    networks:
      - papernet
    depends_on:
      - service_collections
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=false"

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Notes Service                                                              ║
# ╚════════════════════════════════════════════════════════════════════════════╝
  service_notes:
    image: paperwork/service-notes:latest
    env_file:
      - env/service_notes.env
      - env/services_internal.env
    networks:
      - papernet
    depends_on:
      - service_collections
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=false"

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Storages Service                                                           ║
# ╚════════════════════════════════════════════════════════════════════════════╝
  service_storages:
    image: paperwork/service-storages:latest
    env_file:
      - env/service_storages.env
      - env/services_internal.env
    networks:
      - papernet
    depends_on:
      - service_collections
      - service_storages_backend
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=false"

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Journals Service                                                           ║
# ╚════════════════════════════════════════════════════════════════════════════╝
  service_journals:
    image: paperwork/service-journals:latest
    env_file:
      - env/service_journals.env
      - env/services_internal.env
    networks:
      - papernet
    depends_on:
      - service_collections
      - service_events
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=false"

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Web UI                                                                     ║
# ╚════════════════════════════════════════════════════════════════════════════╝
  web:
    image: paperwork/web:latest
    env_file:
      - env/web.env
    networks:
      - papernet
    depends_on:
      - service_gatekeeper
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.protocol=http"
        - "traefik.port=80"
        - "traefik.docker.network=paperwork_papernet"
        - "traefik.backend=web"
        - "traefik.backend.loadbalancer.swarm=true"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.rule=Host:${PAPERWORK_WEB_HOSTNAME:-www}.${PAPERWORK_DOMAIN:-paperwork.local};PathPrefix:/"
